### ISSUE TITLE
Add a comprehensive readme

### ISSUE THREAD

**Issue by EdwinB12** [Romain-Thomas-Shef/dfitspy_RSECon24#1]
The Readme is missing useful information, especially for people finding the software for the first time. 

- [x] A brief description of what the package does 
- [x] Installation
- [x] License

**Comment by Romain-Thomas-Shef** [comment]
Fixed

**Comment by danielskatz** [comment]
tag for the review: https://github.com/openjournals/joss-reviews/issues/7176

**Comment by Romain-Thomas-Shef** [comment]
@EdwinB12 Done. Thank you for the suggestion!
